### ISSUE TITLE
October fails to boot under pop_OS!

### ISSUE THREAD

**Issue by marcus-crane** [marcus-crane/october#100]
Both master branch and v1.5.0 refuse to boot up on a fresh pop_OS! install as I've just discovered. Haven't looked into what just yet.

```
marcus@pop-os:~$ uname -a
Linux pop-os 6.5.4-76060504-generic #202309191142~1695998943~22.04~070916d SMP PREEMPT_DYNAMIC Fri S x86_64 x86_64 x86_64 GNU/Linux
```

Here's some output from `journalctl`:

```
Nov 17 21:08:38 pop-os firefox.desktop[81550]: Unpacking october (1.0.0) ...
Nov 17 21:08:38 pop-os firefox.desktop[81550]: Setting up october (1.0.0) ...
Nov 17 21:08:44 pop-os october.desktop[82221]: Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
Nov 17 21:08:44 pop-os october.desktop[82221]: EGLDisplay Initialization failed: EGL_BAD_ACCESS
Nov 17 21:08:44 pop-os october.desktop[82221]: EGLDisplay Initialization failed: EGL_NOT_INITIALIZED
Nov 17 21:08:44 pop-os october.desktop[82221]: Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
Nov 17 21:08:44 pop-os october.desktop[82221]: fatal error: unexpected signal during runtime execution
Nov 17 21:08:44 pop-os october.desktop[82221]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7f056b3b621f]
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime stack:
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.throw({0x9efbfd?, 0x7f0561e2190b?})
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/panic.go:1047 +0x5d fp=0x7ffcfd9de130 sp=0x7ffcfd9de100 pc=0x443cfd
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.sigpanic()
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/signal_unix.go:823 +0x369 fp=0x7ffcfd9de180 sp=0x7ffcfd9de130 pc=0x459da9
Nov 17 21:08:44 pop-os october.desktop[82221]: goroutine 1 [syscall, locked to thread]:
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.cgocall(0x909480, 0xc0000e1bf0)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/cgocall.go:158 +0x5c fp=0xc0000e1bc8 sp=0xc0000e1b90 pc=0x411e1c
Nov 17 21:08:44 pop-os october.desktop[82221]: github.com/wailsapp/wails/v2/internal/frontend/desktop/linux._Cfunc_SetupWebview(0x27fb730, 0x285c260, 0x0, 0x0)
Nov 17 21:08:44 pop-os october.desktop[82221]:         _cgo_gotypes.go:785 +0x4d fp=0xc0000e1bf0 sp=0xc0000e1bc8 pc=0x82764d
Nov 17 21:08:44 pop-os october.desktop[82221]: github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewWindow.func6(0x27499f0?, 0xc00023a280, 0x0)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/desktop/linux/window.go:92 +0x95 fp=0xc0000e1c38 sp=0xc0000e1bf0 pc=0x82faf5
Nov 17 21:08:44 pop-os october.desktop[82221]: github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewWindow(0xc00023a280, 0x0)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/desktop/linux/window.go:92 +0x1df fp=0xc0000e1ca8 sp=0xc0000e1c38 pc=0x82f53f
Nov 17 21:08:44 pop-os october.desktop[82221]: github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend({0xb027a0?, 0xc0002a2ba0}, 0xc00023a280, 0xc000012f90, 0xc000292840, {0xaff3c0?, 0xc00007fbc0})
Nov 17 21:08:44 pop-os october.desktop[82221]:         /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/desktop/linux/frontend.go:182 +0x5c5 fp=0xc0000e1d88 sp=0xc0000e1ca8 pc=0x82ae45
Nov 17 21:08:44 pop-os october.desktop[82221]: github.com/wailsapp/wails/v2/internal/frontend/desktop.NewFrontend(...)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/desktop/desktop_linux.go:16
Nov 17 21:08:44 pop-os october.desktop[82221]: github.com/wailsapp/wails/v2/internal/app.CreateApp(0xc00023a280)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/app/app_production.go:84 +0x5a5 fp=0xc0000e1eb8 sp=0xc0000e1d88 pc=0x838225
Nov 17 21:08:44 pop-os october.desktop[82221]: github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0xc00028e8c0)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/pkg/application/application.go:57 +0x29 fp=0xc0000e1ed8 sp=0xc0000e1eb8 pc=0x839069
Nov 17 21:08:44 pop-os october.desktop[82221]: github.com/wailsapp/wails/v2.Run(0xc00023a280?)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/wails.go:14 +0xa5 fp=0xc0000e1f00 sp=0xc0000e1ed8 pc=0x839285
Nov 17 21:08:44 pop-os october.desktop[82221]: main.main()
Nov 17 21:08:44 pop-os october.desktop[82221]:         /home/runner/work/october/october/main.go:32 +0x565 fp=0xc0000e1f80 sp=0xc0000e1f00 pc=0x839a85
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.main()
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250 +0x212 fp=0xc0000e1fe0 sp=0xc0000e1f80 pc=0x446592
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.goexit()
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000e1fe8 sp=0xc0000e1fe0 pc=0x474a61
Nov 17 21:08:44 pop-os october.desktop[82221]: goroutine 2 [force gc (idle)]:
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:363 +0xd6 fp=0xc000076fb0 sp=0xc000076f90 pc=0x446956
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.goparkunlock(...)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:369
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.forcegchelper()
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:302 +0xad fp=0xc000076fe0 sp=0xc000076fb0 pc=0x4467ed
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.goexit()
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000076fe8 sp=0xc000076fe0 pc=0x474a61
Nov 17 21:08:44 pop-os october.desktop[82221]: created by runtime.init.6
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:290 +0x25
Nov 17 21:08:44 pop-os october.desktop[82221]: goroutine 3 [GC sweep wait]:
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:363 +0xd6 fp=0xc000077790 sp=0xc000077770 pc=0x446956
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.goparkunlock(...)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:369
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.bgsweep(0x0?)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/mgcsweep.go:278 +0x8e fp=0xc0000777c8 sp=0xc000077790 pc=0x43316e
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.gcenable.func1()
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/mgc.go:178 +0x26 fp=0xc0000777e0 sp=0xc0000777c8 pc=0x427e26
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.goexit()
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000777e8 sp=0xc0000777e0 pc=0x474a61
Nov 17 21:08:44 pop-os october.desktop[82221]: created by runtime.gcenable
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/mgc.go:178 +0x6b
Nov 17 21:08:44 pop-os october.desktop[82221]: goroutine 4 [GC scavenge wait]:
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.gopark(0xc000034070?, 0xafd340?, 0x1?, 0x0?, 0x0?)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:363 +0xd6 fp=0xc000077f70 sp=0xc000077f50 pc=0x446956
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.goparkunlock(...)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:369
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.(*scavengerState).park(0xe4e820)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000077fa0 sp=0xc000077f70 pc=0x431213
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.bgscavenge(0x0?)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc000077fc8 sp=0xc000077fa0 pc=0x4317e5
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.gcenable.func2()
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/mgc.go:179 +0x26 fp=0xc000077fe0 sp=0xc000077fc8 pc=0x427dc6
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.goexit()
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000077fe8 sp=0xc000077fe0 pc=0x474a61
Nov 17 21:08:44 pop-os october.desktop[82221]: created by runtime.gcenable
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/mgc.go:179 +0xaa
Nov 17 21:08:44 pop-os october.desktop[82221]: goroutine 5 [finalizer wait]:
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.gopark(0xe4f220?, 0xc000007860?, 0x0?, 0x0?, 0xc000076770?)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:363 +0xd6 fp=0xc000076628 sp=0xc000076608 pc=0x446956
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.goparkunlock(...)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:369
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.runfinq()
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/mfinal.go:180 +0x10f fp=0xc0000767e0 sp=0xc000076628 pc=0x426f2f
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.goexit()
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000767e8 sp=0xc0000767e0 pc=0x474a61
Nov 17 21:08:44 pop-os october.desktop[82221]: created by runtime.createfing
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/mfinal.go:157 +0x45
Nov 17 21:08:44 pop-os october.desktop[82221]: goroutine 6 [chan receive]:
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:363 +0xd6 fp=0xc0000786d0 sp=0xc0000786b0 pc=0x446956
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.chanrecv(0xc000292780, 0xc0000787a8, 0x1)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/chan.go:583 +0x49b fp=0xc000078760 sp=0xc0000786d0 pc=0x414e1b
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.chanrecv2(0x0?, 0x0?)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/chan.go:447 +0x18 fp=0xc000078788 sp=0xc000078760 pc=0x414958
Nov 17 21:08:44 pop-os october.desktop[82221]: github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).startRequestProcessor(0xc000293aa0)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/desktop/linux/frontend.go:472 +0x5d fp=0xc0000787c8 sp=0xc000078788 pc=0x82c47d
Nov 17 21:08:44 pop-os october.desktop[82221]: github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend.func1()
Nov 17 21:08:44 pop-os october.desktop[82221]:         /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/desktop/linux/frontend.go:173 +0x26 fp=0xc0000787e0 sp=0xc0000787c8 pc=0x82af86
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.goexit()
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000787e8 sp=0xc0000787e0 pc=0x474a61
Nov 17 21:08:44 pop-os october.desktop[82221]: created by github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend
Nov 17 21:08:44 pop-os october.desktop[82221]:         /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/desktop/linux/frontend.go:173 +0x51c
Nov 17 21:08:44 pop-os october.desktop[82221]: goroutine 7 [chan receive]:
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:363 +0xd6 fp=0xc000078ec8 sp=0xc000078ea8 pc=0x446956
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.chanrecv(0xc000292720, 0xc000078fa8, 0x1)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/chan.go:583 +0x49b fp=0xc000078f58 sp=0xc000078ec8 pc=0x414e1b
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.chanrecv2(0x0?, 0x0?)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/chan.go:447 +0x18 fp=0xc000078f80 sp=0xc000078f58 pc=0x414958
Nov 17 21:08:44 pop-os october.desktop[82221]: github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).startMessageProcessor(0x0?)
Nov 17 21:08:44 pop-os october.desktop[82221]:         /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/desktop/linux/frontend.go:190 +0x59 fp=0xc000078fc8 sp=0xc000078f80 pc=0x82b019
Nov 17 21:08:44 pop-os october.desktop[82221]: github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend.func2()
Nov 17 21:08:44 pop-os october.desktop[82221]:         /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/desktop/linux/frontend.go:176 +0x26 fp=0xc000078fe0 sp=0xc000078fc8 pc=0x82af26
Nov 17 21:08:44 pop-os october.desktop[82221]: runtime.goexit()
Nov 17 21:08:44 pop-os october.desktop[82221]:         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000078fe8 sp=0xc000078fe0 pc=0x474a61
Nov 17 21:08:44 pop-os october.desktop[82221]: created by github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend
Nov 17 21:08:44 pop-os october.desktop[82221]:         /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/desktop/linux/frontend.go:176 +0x55f
```

**Comment by marcus-crane** [comment]
Hmm, it seems I've installed something at some point that enabled October to boot up properly. I'll have to redo the processes to figure out what it might have been.

**Comment by marcus-crane** [comment]
Dependencies are now defined as part of the `.deb` file so tools like `gdebi` will prompt the user to install them as prerequisites which should fix this issue

![CleanShot 2023-12-18 at 17 47 00@2x](https://github.com/marcus-crane/october/assets/14816406/a1c8ca33-4572-4e1c-8c32-8f804e094651)
